import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'
import { ReactQueryProvider } from './providers/react-query-provider'
import { CartProvider } from '@/context/cart-context'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full min-h-screen flex flex-col justify-center items-start`}
      >
        <CartProvider>
          <Navbar />
          <main className="w-full h-full flex flex-grow flex-col justify-start items-center">
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </main>
        </CartProvider>
      </body>
    </html>
  )
}
